version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres   # <-- ध्यान दें, पासवर्ड 'postgres' है
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A credit_approval_system worker -l info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
